# Generated by Django 5.2 on 2025-04-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'User Activities'},
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='action',
            new_name='action_type',
        ),
    ]
