# Generated by Django 5.2 on 2025-04-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_useractivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='systemperformance',
            options={'verbose_name': 'System Performance', 'verbose_name_plural': 'System Performances'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.RenameField(
            model_name='systemperformance',
            old_name='api_response_time',
            new_name='cpu_usage',
        ),
        migrations.RenameField(
            model_name='systemperformance',
            old_name='query_time',
            new_name='disk_usage',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='action_type',
            new_name='activity_type',
        ),
        migrations.AddField(
            model_name='systemperformance',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='page_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Summary',
                'verbose_name_plural': 'Activity Summaries',
            },
        ),
        migrations.CreateModel(
            name='LogUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='courseProgress',
        ),
    ]
