# Generated by Django 5.2 on 2025-04-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('last_updated', models.DateField(auto_now=True)),
                ('progress_percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
    ]
