# Generated by Django 5.2 on 2025-04-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProgress',
            new_name='Progress',
        ),
    ]
