# Generated by Django 5.2 on 2025-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_remove_progress_progress_progress_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Test description'),
            preserve_default=False,
        ),
    ]
